import Picture from './components/Picture'
import './styles.css'

function App() {
  return (
    <div>
      <Picture />
    </div>
  );
}

export default App;

//TODO:

//   (DONE)MAKE FRONTEND WITH STATIC PHOTO
//   (DONE)FIGURE OUT HOW TO GET X,Y COORDINATES OF MOUSE CLICK ON PHOTO (EVENTS PROPERTIES?)
//   (DONE)ADD FUNCTIONALITY TO HIGHLIGHT THE CLICKED AREA AND POP UP A DROPDOWN MENU W/ CHARACTER SELECTION
//   (DONE)ADD COORDINATE BOXES TO THE BACKEND CORRELATING TO EACH SELECTABLE CHARACTER IN THE PHOTO(two opposite corners only)
//   (DONE)VALIDATE THE FRONT-END SELECTION AGAINST THE BACKEND COORDINATES
//   (DONE)ADD A TIMER TO THE FRONTEND
//   (DONE)ADD FEEDBACK THAT A CHARACTER HAS BEEN SELECTED CORRECTLY (MAKE A NICE DIV THAT POPS UP TEMPORARILY SOMEHOW)
//ADD LOGIC TO CHECK WHEN ALL THREE CHARACTERS HAVE BEEN FOUND
//ONCE ALL THREE CHARACTERS HAVE BEEN FOUND, POP UP CONGRATULATIONS WITH TIMER

